### ISSUE TITLE
RE-API Test Suite Blog

### ISSUE THREAD

**Issue by LaurenceUrhegyi** [bazelbuild/bazel-blog#192]
Hi everyone,

Myself and some colleagues over at [Codethink](https://www.codethink.co.uk/) (with some contributions from others as well) have been working on a [test suite](https://gitlab.com/remote-apis-testing/remote-apis-testing) for the Remote Execution API. I'm planning to write a blog about our progress and planned next steps, and inviting / encouraging any interested parties to contribute.

Our [Roadmap](https://gitlab.com/remote-apis-testing/remote-apis-testing/wikis/roadmap) has full details of what we've done and what we want to do next.

Do you think this would be of interest to the Bazel blog? I'd like to get a draft done soon, which I could raise as an PR for review.

As for signing the CLA, this should be fine: Codethink already has a few folks signed up.

Thanks,
Laurence

**Comment by buchgr** [comment]
sounds good to me! thanks for doing this laurence!

**Comment by jin** [comment]
Thanks again @LaurenceUrhegyi for your blogpost.
