### ISSUE TITLE
Write a blog post about GSoC

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/bazel-blog#199]
We should write a blog post about GSoC results. I wanted to do it, but I haven't found the time yet.
cc @laszlocsomor, @rongjiecomputer, @Quarz0

https://summerofcode.withgoogle.com/projects/?sp-search=bazel#5320645678727168

**Comment by laszlocsomor** [comment]
I agree, and hadn't had time so far either.

**Comment by jin** [comment]
Any movement on this?

**Comment by laurentlb** [comment]
Obsolete
