### ISSUE TITLE
Transition RSS feed

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel-blog#2]
Today, we have an RSS feed at https://bazel.build/blog/feed.xml
With the new blog, we will host it at https://blogbazel.build/feed.xml

How can we make a smooth transition?

**Comment by steren** [comment]
@davidzchen, what is the plan for the RSS feed?

**Comment by davidzchen** [comment]
/cc @damienmg 

For redirecting from the old feed, I plan to try a XML redirect: http://www.rssboard.org/redirect-rss-feed

**Comment by zerok** [comment]
Hi :) I'm not completely sure if this is related but https://blog.bazel.build/feed.xml points to http://bazel.build inside the channel/link right now. This breaks all the post links :) If this is not related, please let me know, then I'll create a new ticket.

**Comment by jin** [comment]
The feed at https://blog.bazel.build/feed.xml is correct now.
