### ISSUE TITLE
On mobile: navigation menu does not appear on index page

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel-blog#21]
On the index page, the navigation menu does not appear:
![localhost-12345- 14](https://user-images.githubusercontent.com/360895/27732994-2ef42ce4-5d94-11e7-84f1-e944e2cb320b.png)

It appears on post pages:
![localhost-12345-2017-06-28-sjd-unused_deps html](https://user-images.githubusercontent.com/360895/27732995-2fccd01c-5d94-11e7-95ef-5f593151aaa4.png)

**Comment by steren** [comment]
I tried to diagnose, and found out that removing {{content}} in blog.html makes the menu re-appear.
My hypothesis is that one of the posts is interfering with the menu.

**Comment by jin** [comment]
This seems to be fixed. Closing.
