### ISSUE TITLE
Make sure we see have a process in place to monitor incoming Pull Requests on this repo

### ISSUE THREAD

**Issue by steren** [bazelbuild/bazel-blog#23]

**Comment by damienmg** [comment]
Closing because I don't understand what that means

**Comment by steren** [comment]
If somebody sends a PR to this repo, what is it place to make sure the Bazel team sees it?

**Comment by damienmg** [comment]
Oh :)

**Comment by damienmg** [comment]
We actually talked about that earlier today with @helenalt

**Comment by jin** [comment]
I'm currently manually checking the PRs. @helenalt was there a decision on this?

**Comment by jin** [comment]
We have CODEOWNERS that automatically assign PRs to a set of owners now.
