### ISSUE TITLE
broken recommendation re: well known protos in 2017/02/27/protocol-buffers.html

### ISSUE THREAD

**Issue by erickj** [bazelbuild/bazel-blog#56]
The FAQ at https://blog.bazel.build/2017/02/27/protocol-buffers.html has a broken recommendation regarding well known protos.

It says:

"Q: How does one use well-known types? (e.g., any.proto, descriptor.proto)
A: Once google/protobuf#2763 is resolved, the following should be added to a .proto file: import google/protobuf/any.proto and the following: @com_google_protobuf//:well_known_types_protos to one's proto_library rule."

However, with bazel 0.8.0 and a fresh clone of https://github.com/cgrushko/proto_library the referenced target does not exist:

```
$ bazel query @com_google_protobuf//:well_known_types_protos
ERROR: no such target '@com_google_protobuf//:well_known_types_protos': target 'well_known_types_protos' not declared in package '' defined by /home/erick/.cache/bazel/_bazel_erick/b1f9fa8319238652d95ee6d19999542c/external/com_google_protobuf/BUILD
```

I've sent a PR to close https://github.com/cgrushko/proto_library/issues/10 - but the blog post should be updated with information that works with the cgrushko/proto_library repo

**Comment by jin** [comment]
@cgrushko did #60 address this?

**Comment by jin** [comment]
Protobuf rules have evolved quite a bit to rules_proto. Closing this now.
